export const SHOW_FILTER_BAR = 'SHOW_FILTER_BAR'
export const HIDE_FILTER_BAR = 'HIDE_FILTER_BAR'

export const SHOW_MOBILE_MENU = 'SHOW_MOBILE_MENU'
export const HIDE_MOBILE_MENU = 'HIDE_MOBILE_MENU'